#!/bin/bash
#######################################
#
#	Tomoyo After Patch
#		Zenity Version
#
#	Version:
#		git
#
#	Author:
#	    Swiss <swiss@veryoblivio.us>
#
#
#	This doesn't use Bashv4....
#		Stupid mac.
#    This script is meant to install 
#	Tomoyo After with Zenity
#	Deprecated by install
#######################################

##Zenity Functions (to make everything faster)
#non critical error
function zenerror() {
    zenity --error --text="$1"
}
#Yes no question
function zenq() {
    zenity --question --text="$1"
    return $?
}
#info dialog
function zeninfo() {
    zenity --info --text="$1"
}
#Directory selection
function zendir() {
    zenity --file-selection --directory --title="$1" $2
}
#critical error
function zencrit() {
    zenity --error --text="$1"
    exit 1
}
function zencancel() {
    zenity --error --text="Install Cancelled"
    exit 1
}

which rlvm >&2 2>/dev/null || zencrit "RLVM was not found installed on this system. Please install it before attempting to install the patch, as the patch won't work without it.\nRLVM can be found at http://www.elliotglaysher.org/rlvm/"
zenq "Do you already have Tomoyo After installed?"
preinstall=$?

#Install from Disc
if [[ $preinstall -eq 0 ]]; then
    zeninfo "Please specify the location of the disk labeled 'Tomoyo After ~It's a Wonderful Life~'"
    installdisc=$(zendir "Tomoyo After Install Disc")
    [ -f "$installdisc/Seen.txt" ] || [[ -f "$installdisc/SEEN.TXT" ]] || zencrit "Your install location seems to be incorrect or you have a bad disc."
    zeninfo "Please specify the directory Tomoyo After should be installed into \n This creates a new directory of 'Tomoyo After' under whatever directory you specify" "--filename=~/";
    installloc=$(zendir "Destination Directory") || zencancel
    zeninfo "Tomoyo After will now be installed. This may take a while. Press OK to start the installtion." || zencancel
    (
    running=true
    mkdir "$installloc/Tomoyo After/";
	chmod +w "$installloc/Tomoyo After"
	for i in `echo bgm dat dt00.dll Gameexe.ini g00 koe gan manual mov sys wav Seen.txt Tomoyo.ico`
	do
	    cp -r "$installdisc/$i" "$installloc/Tomoyo After/" &
	done
    while [[ $running == "0" ]]
    do
	chmod +w -R "$installloc/Tomoyo After";
	some=$(sed -e "s/ .*$//" << `du -s "$installloc/Tomoyo After"`)
	let " progress = 100 * some / 2146664"
	echo $progress
	if [[ "$progress" -eq 100 ]]
	    then running=false
	fi
    done
    ) |
	zenity  --progress --title="Installing Tomoyo After" --text="Copying Neccessary Files" --percentage=0 || zencancel
	zeninfo "Your Tomoyo After installation is located at $installloc/Tomoyo After/. \n Press OK to continue to installing the patch." || zencancel
fi;
#End Install Disc
#Getting the installation directoy
if [ $preinstall -eq 1 ]; then
    tomodir="$installloc/Tomoyo After"
else
    zeninfo "Please specify the location of your Tomoyo After installation \n (If installed through wine it should be ~/.wine/drive_c/KEY/Tomoyo After/"  || zencancel
    tomodir=$(zendir "Installed Directory")
    #probably a cleaner way to do this ignoring capitilization, but oh well
    [ -e "$tomodir/Gameexe.ini" ] &&	mv "$tomodir/Gameexe.ini" "$tomodir/GAMEEXE.INI"
    [ -e "$tomodir/GAMEEXE.INI" ] || zencrit "This installer cannot find Gameexe.ini or GAMEEXE.INI inside $tomodir. Please doublecheck that you specified the correct directory."
fi
chmod +rw -R "$tomodir"
#Done with their directory

##End of Installation Directory finding, now to copy the patch

#Font first
zeninfo "A font chosen by the designers of the patch will now be placed on your system. Please choose a directory for it to be placed into."
fontdir=$(zendir "Font Directory" "--filename=~/.rlvm/" || zencancel)
cp msgothic.ttc "$fontdir"


#Final time asking before overwriting
zenq "Do you want to continue installing the patch? \n (Last chance to back out)" || zencancel
if [ -e "$tomodir/Seen.txt" ]; then
    m="bgm dat gan koe mov sys wav Seen.txt"
    for i in `echo $m`; do
	if [ -e "$tomodir/$i" ]; then
	    j=$(echo $i | tr '[:lower:]' '[:upper:]' )
	    mv "$tomodir/$i" "$tomodir/$j"
	fi
    done
    chmod +rw -R "$tomodir"
   
   m="SEEN* rlBabel.dll 1.3.5.4.map GAMEEXE.INI G00 MOV"
   for i in `echo $m`;
      do cp $i "$tomodir" -r
   done
fi

#Nice desktop installer
##TO DO make it purty
if [ -e ~/Desktop ];
then
    zenq "Do you want a desktop launcher to be installed to run Tomoyo After?" && (
    echo -e '#!/bin/bash' " \nrlvm --font \042"$fontdir/msgothic.ttc"\042 \042"$tomodir"\042 " > ~/Desktop/TomoyoAfter
    chmod +x ~/Desktop/TomoyoAfter
    zeninfo "A shortcut to run Tomoyo After has been placed on your desktop. If you wish to run Tomoyo After via the command line please execute: \n rlvm --font \042 $fontdir/msgothic.ttc\042 \042 $tomodir \042 "
    )
fi


zeninfo "Thank you for using Doki\'s Tomoyo After installer!"
#EOF, clean exit
exit 0
