#!/bin/bash
##This is gonna be where I start writing what would replace a zenity line

##Erorr
#zenit --error
#2 types, warning and info, i want warning for error
RETURN=$(osascript << EOT
tell app "System Events"
    display alert "MAIN BIG TEXT"
	as warning
	message "Little info text"
end tell
EOT)

#zenity --file-selection --directory
##DONT KNOW IF THIS WILL WORK
RETURN=$(/usr/bin/osascript << EOT
tell app "System Events"
    set NAMEFOLDER to quoted form of POSIX path of (choose folder with prompt "WORDS" default location alias "Volumes")
    get NAMEFOLDER
end tell
EOT)
## MIGHT BE ABLE TO
RETURN=$(/usr/bin/osascript << EOT
tell app "System Events"
    quoted form of POSIX path of (choose folder with prompt "WORDS" default location alias "Volumes")
end tell
EOT)
##GONNA LEAVE THESE HERE!!!
##DESKTOP
DesktopFolder=$(/usr/bin/osascript << EOT
tell app "System Events"
    path to desktop
end tell
EOT)

##Fonts
FontsFolder=$(/usr/bin/osascript << EOT
tell app "System Events"
    path to fonts
end tell
EOT)

which rlvm > /dev/null
if [ "$?" = "1" ];
   then
   zenity --error --text="RLVM was not found installed on this system. Please install it before attempting to install the patch, as the patch won't work without it.\nRLVM can be found at http://www.elliotglaysher.org/rlvm/";
fi
zenity --question \
--text="Do you already have Tomoyo After installed?"
preinstall=$?
#install disc
if [ $preinstall -eq 1 ]; then
   zenity --info --text="Please specify the location of 'Tomoyo After ~It's a Wonderful Life~'"
   installdisc=$(zenity --file-selection --directory --title="Tomoyo After Install Disc");
   if [ -f "$installdisc/Seen.txt" ]; then
   zenity --info --text="Please specify the directory Tomoyo After should be installed into \n This creates a new directory of 'Tomoyo After' under whatever directory you specify";
   else
   zenity --info --text="Your install location seems to be incorrect or you have a bad disc."
   exit 0
   fi
   installloc=$(zenity --file-selection --directory --title="Destination Directory");
   if [ $? -eq 1 ];
   then exit 0
   fi
   zenity --info --text="Tomoyo After will now be installed. This may take a while. Press OK to start the installtion."
   (
   running=1
   mkdir "$installloc/Tomoyo After/";
	chmod +w "$installloc/Tomoyo After";
   	for i in `echo bgm dat dt00.dll Gameexe.ini g00 koe gan manual mov sys wav Seen.txt Tomoyo.ico`; 
		do cp -r "$installdisc/$i" "$installloc/Tomoyo After/" &
	done
   while [ $running -eq 1 ];
   do
	chmod +w -R "$installloc/Tomoyo After";
	some=$(sed -e "s/ .*$//" <<< `du -s "$installloc/Tomoyo After"`)
	let " progress = 100 * some / 2146664"
	echo $progress
	if [ "$progress" -eq 100 ]
		then running=0
	fi
	done
	) |
	zenity  --progress --title="Installing Tomoyo After" --text="Copying Neccessary Files" --percentage=0
		if [ "$?" = -1 ] ; 
		then
			zenity --error --text="Installation cancelled."
			exit 0
		fi; 
	zenity --info --text="Your Tomoyo After installation is located at $installloc/Tomoyo After/. \n Press OK to continue to installing the patch.";
	if [ $? -eq 1 ]; then 
		exit 0
	fi;
   else
   sleep 0;
fi;
#End Install Disc
#Getting the installation directoy
if [ $preinstall -eq 1 ]; then
   tomodir="$installloc/Tomoyo After"
else
   zenity --info --text="Please specify the location of your Tomoyo After installation \n (If installed through wine it should be ~/.wine/drive_c/KEY/Tomoyo After/"
   tomodir=$(zenity --file-selection --directory --title="Installed Directory");
   #probably a cleaner way to do this ignoring capitilization
   if [ -e "$tomodir/Gameexe.ini" ]; then
   	mv "$tomodir/Gameexe.ini" "$tomodir/GAMEEXE.INI"
   else 
   	if [ -e "$tomodir/GAMEEXE.INI" ]; then
	   sleep 0
	else
#Failed check
	   zenity --info --text="This installer cannot find Gameexe.ini or GAMEEXE.INI inside $tomodir. Please doublecheck that you specified the correct directory."
	   exit 0
	fi
   fi
fi
chmod +rw -R "$tomodir"
#End of Installation Directory finding, now to copy the patch
#Font first
zenity --info --text="A font chosen by the designers of the patch will now be placed on your system. Please choose a directory for it to be placed into."
fontdir=$(zenity --file-selection --directory --title="Font Directory" --filename=~/.rlvm/)
if [ "$?" -eq "1" ];
   then exit 0 ;
fi
cp msgothic.ttc "$fontdir"


#Final time asking
zenity --question --text="Do you want to continue installing the patch? \n (Last chance to back out)"
if [ "$?" -eq 1 ];
   then exit 0;
fi
##WILL NEED EDITING FOR THE REAL FILES
if [ -e "$tomodir/Seen.txt" ]; then
   m="bgm dat gan koe mov sys wav Seen.txt"
   for i in `echo $m`; do
      if [ -e "$tomodir/$i" ]; then
         j=$(echo $i | tr '[:lower:]' '[:upper:]' )
	 mv "$tomodir/$i" "$tomodir/$j"
     fi
   done


chmod +rw -R "$tomodir"
   
   m="SEEN* rlBabel.dll 1.3.5.4.map GAMEEXE.INI G00 MOV"
   for i in `echo $m`;
      do cp $i "$tomodir" -r
   done
fi

#Nice desktop installer
##TO DO make it purty
if [ -e ~/Desktop ];
   then
   zenity --question --text="Do you want a desktop launcher to be installed to run Tomoyo After?"
   if [ "$?" -eq "0" ];
      then
      echo -e '#!/bin/bash' " \nrlvm --font \042"$fontdir/msgothic.ttc"\042 \042"$tomodir"\042 " > ~/Desktop/TomoyoAfter
      chmod +x ~/Desktop/TomoyoAfter
      zenity --info --text="A shortcut to run Tomoyo After has been placed on your desktop. If you wish to run Tomoyo After via the command line please execute: \n rlvm --font \042 $fontdir/msgothic.ttc\042 \042 $tomodir \042 "
   fi
fi


zenity --info --text="Thank you for using Doki\'s Tomoyo After installer!"
#EOF
exit 0


# vim: tw=80 sw=4 : 
